Load the requisite libraries.

In [2]:
import pandas as pd
import numpy as np

Load the data frames:

In [3]:
schools = pd.read_csv("/Users/wratko/Documents/projects/tx-school_funding/jupyter-notebooks/bexar-county-schools - trad_ISD_CSD.csv")
data = pd.read_csv("/Users/wratko/Documents/projects/tx-school_funding/jupyter-notebooks/econ-disadv_data.csv")

In [4]:
display(schools,data)

,City,District,Charter Status,District #,Campus,Campus #,Grade Group
0,San Antonio,Alamo Heights ISD,Traditional ISD/CSD,15901,ALAMO HEIGHTS H S,15901001,High School
1,San Antonio,Alamo Heights ISD,Traditional ISD/CSD,15901,ALAMO HEIGHTS J H,15901041,Middle School
2,San Antonio,Alamo Heights ISD,Traditional ISD/CSD,15901,CAMBRIDGE EL,15901101,Elementary
3,San Antonio,Alamo Heights ISD,Traditional ISD/CSD,15901,HOWARD EL,15901102,Elementary
4,San Antonio,Alamo Heights ISD,Traditional ISD/CSD,15901,WOODRIDGE EL,15901104,Elementary
...,...,...,...,...,...,...,...
450,San Antonio,Southwest ISD,Traditional ISD/CSD,15912,SOUTHWEST EL,15912101,Elementary
451,San Antonio,Southwest ISD,Traditional ISD/CSD,15912,SOUTHWEST H S,15912001,High School
452,San Antonio,Southwest ISD,Traditional ISD/CSD,15912,SOUTHWEST LEGACY H S,15912005,High School
453,San Antonio,Southwest ISD,Traditional ISD/CSD,15912,SPICEWOOD PARK EL,15912110,Elementary
454,San Antonio,Southwest ISD,Traditional ISD/CSD,15912,SUN VALLEY EL,15912102,Elementary

,Campus,Pct Total 2019-20,Pct Total 2018-19,Free and Reduced Lunch Students [Public School] 2019-20,Free and Reduced Lunch Students [Public School] 2018-19,Total Students All Grades (Excludes AE) [Public School] 2019-20,Total Students All Grades (Excludes AE) [Public School] 2018-19
0,21ST CENTURY EARLY LEARNING FOUNDATIONS ACADEMY,99.60%,99.60%,520,512,522,514
1,3D ACADEMY,93.20%,96.20%,136,152,146,158
2,A & M CONS H S,35.60%,35.40%,655,624,1840,1763
3,A & M CONSOLIDATED MIDDLE,44.10%,39.40%,308,278,699,706
4,A B DUNCAN COLLEGIATE EL,79.50%,82.90%,333,355,419,428
...,...,...,...,...,...,...,...
8478,ZEPHYR SCHOOL,57.30%,61.50%,121,134,211,218
8479,ZILKER EL,17.70%,17.90%,88,94,497,524
8480,ZUE S BALES INT,15.30%,16.30%,96,103,626,632
8481,ZUNDELOWITZ EL,87.00%,90.10%,489,510,562,566
8482,ZWINK EL,46.60%,47.80%,497,532,1067,1113

In [5]:
ed_data = pd.merge(schools,data,on="Campus")

In [6]:
display(ed_data)

,City,District,Charter Status,District #,Campus,Campus #,Grade Group,Pct Total 2019-20,Pct Total 2018-19,Free and Reduced Lunch Students [Public School] 2019-20,Free and Reduced Lunch Students [Public School] 2018-19,Total Students All Grades (Excludes AE) [Public School] 2019-20,Total Students All Grades (Excludes AE) [Public School] 2018-19
0,San Antonio,Alamo Heights ISD,Traditional ISD/CSD,15901,ALAMO HEIGHTS H S,15901001,High School,16.90%,16.80%,282,270,1664,1606
1,San Antonio,Alamo Heights ISD,Traditional ISD/CSD,15901,ALAMO HEIGHTS J H,15901041,Middle School,20.00%,20.10%,222,225,1111,1121
2,San Antonio,Alamo Heights ISD,Traditional ISD/CSD,15901,CAMBRIDGE EL,15901101,Elementary,23.20%,23.10%,192,193,826,836
3,San Antonio,Alamo Heights ISD,Traditional ISD/CSD,15901,HOWARD EL,15901102,Elementary,23.40%,22.90%,103,95,441,415
4,San Antonio,Alamo Heights ISD,Traditional ISD/CSD,15901,WOODRIDGE EL,15901104,Elementary,18.70%,19.90%,168,176,899,886
...,...,...,...,...,...,...,...,...,...,...,...,...,...
579,San Antonio,Southwest ISD,Traditional ISD/CSD,15912,SOUTHWEST H S,15912001,High School,72.10%,74.60%,1460,1505,2024,2018
580,San Antonio,Southwest ISD,Traditional ISD/CSD,15912,SOUTHWEST H S,15912001,High School,81.70%,80.20%,1119,1070,1370,1334
581,San Antonio,Southwest ISD,Traditional ISD/CSD,15912,SOUTHWEST LEGACY H S,15912005,High School,95.70%,92.00%,1838,1720,1920,1869
582,San Antonio,Southwest ISD,Traditional ISD/CSD,15912,SPICEWOOD PARK EL,15912110,Elementary,95.80%,96.90%,508,469,530,484
583,San Antonio,Southwest ISD,Traditional ISD/CSD,15912,SUN VALLEY EL,15912102,Elementary,76.70%,80.10%,514,492,670,614

In [7]:
ed_data.to_csv("/Users/wratko/Documents/projects/tx-school_funding/data/Econ-Disadntage_TX-2018-19_ELSI.csv")